#Introducción a la librería "pandas" de Python

Teniendo la siguiente información de los diferentes módulos del *Curso de Especialización en Inteligencia Artificial y Big Data*, realiza los siguientes ejercicios.

| Nombre del Módulo                         | Código  | Horas  |
| ------------------------------------------| ------  | ------ |
| Modelos de Inteligencia Artificial        | M2D     | 60 h   |
| Sistemas de aprendizaje automático        | SNS     | 100 h  |
| Programación de Inteligencia Artificial   | 7RO     | 210 h  |
| Sistemas de Big Data                      | SPS     | 100 h  |
| Big Data aplicado                         | BIU     | 160 h  |
|                                           |         |        |

##Ejercicio 1
Crea una serie usando listas que almacene la duración de los diferentes módulos del *Curso de Especialización en Inteligencia Artificial y Big Data*

In [2]:
import pandas as pd
dur = [60, 100, 210, 100, 160]

series_horas = pd.Series(dur)
display(series_horas)

0     60
1    100
2    210
3    100
4    160
dtype: int64

##Ejercicio 2
Crea una serie usando listas que almacene el nombre completo de los diferentes módulos del *Curso de Especialización en Inteligencia Artificial y Big Data*. Haz lo propio con los códigos de los módulos.

In [7]:
mod = ['M2D', 'SNS', '7RO', 'SPS', 'BIU']

series_mod = pd.Series(mod)
display(series_mod)

0    M2D
1    SNS
2    7RO
3    SPS
4    BIU
dtype: object

##Ejercicio 3
Muestra la duración de aquellos módulos con más de 200 horas.

In [5]:
horas_mod = pd.Series(dur)
horas_mod[horas_mod > 200]

2    210
dtype: int64

##Ejercicio 4
Muestra la serie con los nombres de los módulos en orden ascendente.

In [8]:
nom_mod = pd.Series(mod)
nom_mod.sort_values()

2    7RO
4    BIU
0    M2D
1    SNS
3    SPS
dtype: object

#Ejercicio 5
Crea un DataFrame con las series anteriores y muéstralo por pantalla. A continuación, haz que el código de los módulos sea el índice del DataFrame.

In [12]:
series_nombre = pd.Series(['Modelos de Inteligencia Artificial', 'Sistemas de aprendizaje automático', 'Programación de Inteligencia Artificial', 'Sistemas de Big Data', 'Big Data aplicado'])
df = pd.DataFrame({"Nombre": series_nombre, 'Horas': series_horas, 'Modulos': series_mod})
df.set_index('Modulos')

                                          Nombre  Horas
Modulos
M2D           Modelos de Inteligencia Artificial     60
SNS           Sistemas de aprendizaje automático    100
7RO      Programación de Inteligencia Artificial    210
SPS                         Sistemas de Big Data    100
BIU                            Big Data aplicado    160

#Ejercicio 6
Muestra los datos correspondientes a la fila con índice 2 del DataFrame. Haz lo propio con los datos correspondientes a BIU.

In [14]:
display(df.loc[2])
display(df.loc[df["Modulos"]=="BIU"])

Nombre     Programación de Inteligencia Artificial
Horas                                          210
Modulos                                        7RO
Name: 2, dtype: object

              Nombre  Horas Modulos
4  Big Data aplicado    160     BIU

#Ejercicio 7
Carga en un DataFrame los datos del fichero **insurance.csv**. A continuación, muestra su forma (atributo **shape**) y todos sus datos.

In [15]:
df_csv = pd.read_csv("insurance.csv")

display(df_csv.shape)
display(df_csv)

(1338, 7)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#Ejercicio 8
Muestra los datos de la fila 3 del DataFrame. A continuación, muestra la media de edad de las personas cuyos datos están almacenados en el DataFrame y la proporción de mujeres existentes con respecto al total de personas.

In [19]:
display(df_csv.loc[3])
print(df_csv["age"].mean())
display(df_csv["sex"].value_counts(normalize=True))

age                  33
sex                male
bmi              22.705
children              0
smoker               no
region        northwest
charges     21984.47061
Name: 3, dtype: object

39.20702541106129

sex
male      0.505232
female    0.494768
Name: proportion, dtype: float64

#Ejercicio 9
Crea una copia del DataFrame e inserta en esta copia una nueva fila con unos datos ficticios. Muestra por pantalla los tres últimos registros del DataFrame original y los tres últimos registros de la copia.

In [23]:
cp_df = df_csv.copy()

cp_df.loc[len(cp_df)] = {
    "age": 25,
    "sex": "male",
    "bmi": 24.5,
    "children": 1,
    "smoker": "no",
    "region": "southwest",
    "charges": 3000.0
}

display(df_csv.tail(3))
display(cp_df.tail(3))

      age     sex    bmi  children smoker     region     charges
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

      age     sex    bmi  children smoker     region     charges
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603
1338   25    male  24.50         1     no  southwest   3000.0000

#Ejercicio 10
Haciendo uso del método *query()* del DataFrame, obtén las edades de los que han pagado más de 10000 dólares.

In [24]:
display(df_csv.query("charges > 10000")["age"] )

0       19
3       33
9       60
11      62
13      56
        ..
1330    57
1331    23
1332    52
1333    50
1337    61
Name: age, Length: 626, dtype: int64